// Un swit X est Categorisé ArticleCategory = Chaussure
// Or ArticleCategory:Chaussure Appartient au ArticleTheme = Mode
// Un user U va filtrer ses tendances avec ArticleTheme: Mode
// Or ArticleTheme = Mode => Affiche les ArticleCategory:Chaussures, Vêtement...
// X va être affiché

module.exports = [
    {
        title: 'Autre',
        slug: 'other',
        scrapping_id: 'mol5vjb74aboy',
        articletheme_slug: 'other',
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        title: 'Vetement',
        slug: 'clothe',
        scrapping_id: 'mol5vjb6t1qrs',
        articletheme_slug: 'mode',
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        title: 'Lingerie',
        slug: 'lingerie',
        scrapping_id: 'mol5vjb6t3g17',
        articletheme_slug: 'mode',
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        title: 'Chaussure',
        slug: 'shoe',
        scrapping_id: 'mol5vjb6t3uia',
        articletheme_slug: 'mode',
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        title: 'Maroquinerie-Bag',
        slug: 'leatherbag',
        scrapping_id: 'mol5vjb6talsq',
        articletheme_slug: 'mode',
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        title: 'Collier',
        slug: 'necklace',
        scrapping_id: 'mol5vjb6tb8zs',
        articletheme_slug: 'blingbling',
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        title: 'Bague',
        slug: 'ring',
        scrapping_id: 'mol5vjb6tbqvf',
        articletheme_slug: 'blingbling',
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        title: 'Bracelet',
        slug: 'bracelet',
        scrapping_id: 'mol5vjb6tcftr',
        articletheme_slug: 'blingbling',
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        title: "Boucle d'oreille",
        slug: 'earring',
       	scrapping_id: 'mol5vjb6tdlnu',
        articletheme_slug: 'blingbling',
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        title: 'Montre',
        slug: 'watch',
        scrapping_id: 'mol5vjb6te1ig',
        articletheme_slug: 'blingbling',
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        title: 'Piercing',
        slug: 'piercing',
        scrapping_id: 'mol5vjb6tefxa',
        articletheme_slug: 'blingbling',
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        title: 'Maquillage',
        slug: 'makeup',
        scrapping_id: 'mol5vjb6tetmb',
        articletheme_slug: 'careandbeauty',
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        title: 'Parfum',
        slug: 'perfume',
        scrapping_id: 'mol5vjb6tf6e9',
        articletheme_slug: 'careandbeauty',
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        title: 'Soin',
        slug: 'care',
        scrapping_id: 'mol5vjb6tfv10',
        articletheme_slug: 'careandbeauty',
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        title: 'Parapharmacie',
        slug: 'drugstore',
        scrapping_id: 'mol5vjb6tg83f',
        articletheme_slug: 'careandbeauty',
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        title: 'Decoration',
        slug: 'decoration',
        scrapping_id: 'mol5vjb6wl7jq',
        articletheme_slug: 'decorationanddoityourself',
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        title: 'Linge de maison',
        slug: 'Linen',
        scrapping_id: 'mol5vjb6wlnmj',
        articletheme_slug: 'decorationanddoityourself',
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        title: 'Vaisselle',
        slug: 'washingup',
        scrapping_id: 'mol5vjb6wm0gk',
        articletheme_slug: 'decorationanddoityourself',
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        title: 'Meuble',
        slug: 'furniture',
        scrapping_id: 'mol5vjb6wmbkd',
        articletheme_slug: 'decorationanddoityourself',
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        title: 'Bricolage',
        slug: 'housing',
        scrapping_id: 'mol5vjb6wmrb0',
        articletheme_slug: 'decorationanddoityourself',
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        title: 'Jardinage',
        slug: 'gardening',
        scrapping_id: 'mol5vjb6wn2pu',
        articletheme_slug: 'decorationanddoityourself',
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        title: 'Accessoire multimedia',
        slug: 'multimediaaccessory',
        scrapping_id: 'mol5vjb6wnikj',
        articletheme_slug: 'electronic',
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        title: 'Ordinateur',
        slug: 'computer',
        scrapping_id: 'mol5vjb6wnyf5',
        articletheme_slug: 'electronic',
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        title: 'Tablette',
        slug: 'tablet',
        scrapping_id: 'mol5vjb6woatd',
        articletheme_slug: 'electronic',
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        title: 'Smartphone',
        slug: 'smartphone',
        scrapping_id: 'mol5vjb6wokel',
        articletheme_slug: 'electronic',
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        title: 'Opticien',
        slug: 'optician',
        scrapping_id: 'mol5vjb73vgkj',
        articletheme_slug: 'careandbeauty',
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        title: 'Photo-Image',
        slug: 'picture',
        scrapping_id: 'mol5vjb73wguz',
        articletheme_slug: 'electronic',
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        title: 'Son-Hifi',
        slug: 'hifi',
        scrapping_id: 'mol5vjb73wz29',
        articletheme_slug: 'electronic',
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        title: 'video',
        slug: 'video',
        scrapping_id: 'mol5vjb73xmq1',
        articletheme_slug: 'electronic',
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        title: 'Jeux Video',
        slug: 'videogame',
        scrapping_id: 'mol5vjb73y332',
        articletheme_slug: 'electronic',
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        title: 'Petit electromenager',
        slug: 'smallhomeappliance',
        scrapping_id: 'mol5vjb73yhk2',
        articletheme_slug: 'electronic',
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        title: 'Grand electromenager',
        slug: 'bighomeappliance',
        scrapping_id: 'mol5vjb73yvk6',
        articletheme_slug: 'electronic',
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        title: 'Musique',
        slug: 'music',
        scrapping_id: 'mol5vjb73zboh',
        articletheme_slug: 'sportandleisure',
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        title: 'Livre',
        slug: 'book',
        scrapping_id: 'mol5vjb73zrc4',
        articletheme_slug: 'sportandleisure',
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        title: 'Jeux',
        slug: 'game',
        scrapping_id: 'mol5vjb740bj5',
        articletheme_slug: 'sportandleisure',
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        title: 'Spectacle',
        slug: 'show',
        scrapping_id: 'mol5vjb740syh',
        articletheme_slug: 'sportandleisure',
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        title: 'Sport',
        slug: 'sport',
        scrapping_id: 'mol5vjb7419iw',
        articletheme_slug: 'sportandleisure',
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        title: 'Voyage',
        slug: 'trip',
        scrapping_id: 'mol5vjb741o2d',
        articletheme_slug: 'voyage',
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        title: 'Appartement',
        slug: 'appartment',
        scrapping_id: 'mol5vjb742457',
        articletheme_slug: 'realestate',
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        title: 'Maison',
        slug: 'house',
        scrapping_id: 'mol5vjb742bwg',
        articletheme_slug: 'decorationanddoityourself',
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        title: 'Voiture',
        slug: 'car',
        scrapping_id: 'mol5vjb747a3u',
        articletheme_slug: 'automobile',
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        title: 'Moto',
        slug: 'motorbike',
        scrapping_id: 'mol5vjb747m84',
        articletheme_slug: 'automobile',
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        title: 'Piece auto ',
        slug: 'carpart ',
        scrapping_id: 'mol5vjb7480h0',
        articletheme_slug: 'automobile',
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        title: 'Fourniture papeterie',
        slug: 'stationerysupply',
        scrapping_id: 'mol5vjb748gs7',
        articletheme_slug: 'decorationanddoityourself',
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        title: 'Vin',
        slug: 'wine',
        scrapping_id: 'mol5vjb748toc',
        articletheme_slug: 'deli',
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        title: 'Epicerie fine',
        slug: 'deli',
        scrapping_id: 'mol5vjb749dik',
        articletheme_slug: 'deli',
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        title: 'Alcool',
        slug: 'Alcohol',
        scrapping_id: 'mol5vjb749ws9',
        articletheme_slug: 'deli',
        created_at: new Date(),
        updated_at: new Date(),
    },
];
